class dbupdate{
    constructor()
    {
        this.value = {},
        this.condition={},
        this.andcondition=[],
        this.orcondition=[],
        this.response={},
        this.jsonsuccess={},
        this.jsonfail={},
        this.jsonerror={}
    }
    setvalue(value1){
        value=value1
    }
    setcondition(condition1){
        condition=condition1
    }
    setandcondition(andcondition1){
        andcondition=andcondition1
    }
    setorcondition(orcondition1){
        orcondition=orcondition1
    }
    setresponse(response1){
        response=response1
    }
    setjsonsuccess(jsonsuccess1){
        jsonsuccess=jsonsuccess1
    }
    setjsonfail(jsonfail1){
        jsonfail=jsonfail1
    }
    setjsonerror(jsonerror1){
        jsonerror=jsonerror1
    }

    getvalue(value1){
        value=value1
    }
    getcondition(condition1){
        condition=condition1
    }
    getandcondition(andcondition1){
        andcondition=andcondition1
    }
    getorcondition(orcondition1){
        orcondition=orcondition1
    }
    getresponse(response1){
        response=response1
    }
    getjsonsuccess(jsonsuccess1){
        jsonsuccess=jsonsuccess1
    }
    getjsonfail(jsonfail1){
        jsonfail=jsonfail1
    }
    getjsonerror(jsonerror1){
        jsonerror=jsonerror1
    }

}